import { Inter } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/components/TanstackProvider/TanstackProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "Dua & Ruqyah",
  description: "Collection of duas",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/icons/nav/support.svg",
        href: "/icons/nav/support.svg",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/icons/nav/support.svg",
        href: "/icons/nav/support.svg",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-300 fixed inset-0 px-10`}>
        <TanstackProvider>{children}</TanstackProvider>
      </body>
    </html>
  );
}
